#! /bin/bash

# WARNING This will NUKE DOCKER

OLD_DIR=$(pwd)
cd /home/anon/repos/ivystopia.github.io/scripts/files/docker-compose

echo "docker-compose down"
docker-compose down --remove-orphans --timeout=30
docker-compose down --remove-orphans --timeout=10
docker-compose down --remove-orphans --timeout=5
sleep 5

echo "Force kill anything still running"
docker rm -fv $(docker ps -aq) 2>/dev/null
sleep 5
docker rm -fv $(docker ps -aq) 2>/dev/null
echo "---------"

echo "The following ports are listening:"
sudo lsof -i -P -n
set +x
cd $OLD_DIR
