services:
  monero-node:
    container_name: Monero-Node
    image: ghcr.io/sethforprivacy/simple-monerod:latest
    restart: unless-stopped
    network_mode: bridge
    logging:
      options:
        max-size: "10m"
        max-file: "1"
    env_file:
      - .env
    volumes:
      - /home/anon/.bitmonero:/home/monero/.bitmonero
      - ./monero-node-resolv.conf:/etc/resolv.conf
    ports:
      - "18080:18080" # P2P network port
      - "18081:18081" # RPC full port - Authentication is set. Not open to Internet.
      - "18083:18083" # ZeroMQ port
    command: >
      --out-peers 512
      --in-peers 512
      --enable-dns-blocklist
      --data-dir /home/monero/.bitmonero
      --limit-rate 92160
      --enforce-dns-checkpointing
      --db-sync-mode fast:async:250000000bytes
      --log-level 0
      --max-log-file-size 6553600
      --max-log-files 16
      --rpc-bind-ip 0.0.0.0
      --confirm-external-bind
      --zmq-pub=tcp://0.0.0.0:18083
      --rpc-login $RPC_USERNAME:$RPC_PASSWORD
    environment:
      - TERM="xterm-256color"
    healthcheck:
      test: ["CMD", "curl", "--user", "$RPC_USERNAME:$RPC_PASSWORD", "--fail", "http://localhost:18081/get_info"]
      interval: 30s
      timeout: 5s
      retries: 3

  portainer:
    container_name: Portainer
    image: portainer/portainer-ce:latest
    ports:
      - "9000:9000"
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    command: |
      -H
      unix:///var/run/docker.sock

  pihole:
    container_name: Pi-hole
    image: pihole/pihole:latest
    env_file:
      - .env
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "3141:80/tcp"
    environment:
      TZ: 'Europe/London'
      WEBPASSWORD: $PIHOLE_PASSWORD
    volumes:
      - pihole_data:/etc/pihole
      - dnsmasq_data:/etc/dnsmasq.d
    restart: unless-stopped

volumes:
  portainer_data:
  pihole_data:
  dnsmasq_data:
